### ISSUE TITLE
Voodool2C.kext故障

### ISSUE THREAD

**Issue by shionphan** [stonexing/Asus-S4000VA8550-Hackintosh#2]
显示加载不了驱动
Halting on critical error
使用版本：使用EFI for Big Sur 11.0.1能正常安装10.15 Catalina
解决方案：OC中Kernel设置中禁用VoodooI2C，kext目录驱动也移除VoodooI2C，安装时外接键盘、鼠标

**Comment by stonexing** [comment]
VoodooI2C是触摸板驱动 11.0.1没有仔细搞
触摸板一直将就着用
兄弟如果是一样的机型， 调完美后 记得把完美的efi分享给我哈
