### ISSUE TITLE
CPU core is reduced to 0.5GHz after a long sleep ?

### ISSUE THREAD

**Issue by Jie2GG** [stonexing/Asus-S4000VA8550-Hackintosh#4]
Is your CPU monitor frequency consistent with my description? After a long sleep, the CPU will start to slow down

**Comment by stonexing** [comment]
I have notice that my conputer run slowly. 
And after I force enable trim. then I think my computer run nearly normal as the speed of 8550 cpu.

about how to enable trim you can get help from google

**Comment by Jie2GG** [comment]
OK, thank you for your reply
